# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-15 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0044_auto_20190225_2014'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.DeleteModel("CraftingRecipe"),
                              migrations.DeleteModel("CraftingMaterialType"),
                              migrations.DeleteModel("CraftingMaterials"),
                              ],
        )
    ]
