# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0046_move_models'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CraftingRecipe',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                        ('desc', models.TextField(blank=True, null=True)),
                        ('primary_amount', models.PositiveSmallIntegerField(blank=0, default=0)),
                        ('secondary_amount', models.PositiveSmallIntegerField(blank=0, default=0)),
                        ('tertiary_amount', models.PositiveSmallIntegerField(blank=0, default=0)),
                        ('difficulty', models.PositiveSmallIntegerField(blank=0, default=0)),
                        ('additional_cost', models.PositiveIntegerField(blank=0, default=0)),
                        ('ability', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                        ('skill', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                        ('type', models.CharField(blank=True, max_length=80, null=True)),
                        ('level', models.PositiveSmallIntegerField(blank=1, default=1)),
                        ('result', models.TextField(blank=True, null=True)),
                        ('allow_adorn', models.BooleanField(default=True)),
                        ('lock_storage', models.TextField(blank=True, help_text='defined in setup_utils', verbose_name='locks')),
                    ],
                    options={
                        'abstract': False,
                        'indexes': [],
                    },
                ),
            ],
        ),
    ]
