# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name=b'craftingrecipe_secondary_materials',
            name=b'craftingrecipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CraftingRecipe_secondary_materials+', to='crafting.CraftingRecipe'),
        ),
    ]
